name: Git Actions Demo

on: 
  - push 

jobs:
  actions_demo:
    runs-on: ubuntu-latest 
    steps:
    - run: echo "Hello there!"
    - run: touch file.txt
    - run: echo 'Hello again!' >> file.txt
    - run: cat file.txt 
    - run: ls -a
    - run: pwd
    - run: echo "$USER"
    - run: git clone https://github.com/D-I-code/my_qa_repo_nov22.git
    - run: cat my_qa_repo_nov22/README.md
  
