name: Git Actions Demo

on: 
  - push 

jobs:
  actions_demo:
    runs-on: ubuntu-latest 
    steps:
    - run: git-cat README.md
    - run: echo "Hello there!"
    - run: touch file.txt
    - run: echo 'Hello again!' >> file.txt
    - run: cat file.txt 
    - run: ls -a
    - run: echo "$USER"
    - run: pwd
  
